### ISSUE TITLE
Syntax error in python bindings

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-manipulation-corba#80]
When I try to use the following method in python, I get a syntax error, probably because "from" is a keyword in python.
https://github.com/humanoid-path-planner/hpp-manipulation-corba/blob/2fe0f6c25f9119298d77861c3fe1fbcc00b53f70/idl/hpp/manipulation_idl/_graph.idl#L97

@jmirabel , do  you also have this problem ?

**Comment by jmirabel** [comment]
I hadn't thought about this. Yes, I have the same issue and I just discovered that you must use _from instead.

**Comment by florent-lamiraux** [comment]
I am about to replace methods from ant to in class Edge by stateFrom and stateTo.
What do you think ?

**Comment by jmirabel** [comment]
This is easier than *to* and *_from*.
It is a good first exercise to learn to do the bindings.
