### ISSUE TITLE
Filter transitions

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-manipulation-corba#98]
https://github.com/humanoid-path-planner/hpp-manipulation-corba/blob/2f1c5592ac21218c377fd008f79adf14518569fa/src/hpp/corbaserver/manipulation/constraint_graph_factory.py#L296
I think we should add a call to a new method called "transitionIsAllowed" here to filter out transitions where an object moves without being grasps. This happens when stacking boxes equipped with grippers and handles.

**Comment by jmirabel** [comment]
We already planned paths for scenarios with objects (like a tool) with grippers and handles. We always managed to generate the graph using rules (I think, but we may also have modified the generated graph).

Out of curiosity, what is the case that requires you to add this function ?

**Comment by florent-lamiraux** [comment]
The use case is a forklift that is required to stack boxes on top of each other.
- box2 is put on box1 using gripper "box1/top3 and handle "box2/bottom".
- The boxes are placed on the ground using contact surfaces.
State "box1/top grasps box2/bottom" is allowed. It corresponds to box1 put on the ground and box2 put on box1.
The factory builds a transition between "free" and this latter state although box2 cannot climb on box1 by itself. This type of situation may certainly be detected automatically.

**Comment by jmirabel** [comment]
Then, there is a bug in the Python factory. Normally, an object that is not grasped cannot be moved so box1 should not be movable.

**Comment by florent-lamiraux** [comment]
I would not call that a bug. Method ConstraintGraphFactory._recurse does not make any difference between objects and robots. As it is implemented now, it requests "box1/top" to grasp "box2/bottom" without realizing that "box1" is an object.

**Comment by jmirabel** [comment]
After an oral discussion, the problem is that the graph contains infeasible transition (they are truly infeasible) rather that not generating them.

**Comment by florent-lamiraux** [comment]
Solved by https://github.com/humanoid-path-planner/hpp-manipulation-corba/pull/99.
